# Generated by Django 3.1.4 on 2021-01-26 19:18

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210126_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_project_image),
        ),
    ]
