# Generated by Django 3.1.4 on 2021-01-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210126_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
