# Generated by Django 3.1.4 on 2021-01-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201228_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='meta_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
    ]
