# Generated by Django 3.1.4 on 2021-01-13 01:11

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210113_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_bleach.models.BleachField(),
        ),
    ]
