# Generated by Django 3.1.4 on 2021-01-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210123_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default="This category hasn't a description yet", null=True),
        ),
    ]
