# Generated by Django 3.1.4 on 2021-01-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='description',
            field=models.TextField(blank=True, default="<django.db.models.fields.CharField> <django.db.models.fields.CharField> doesn't have a description yet", max_length=400, null=True),
        ),
    ]
