# Generated by Django 3.1.4 on 2021-01-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_bloguser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='description',
            field=models.TextField(blank=True, default="This User doesn't have a description yet", max_length=400, null=True),
        ),
    ]
