# Generated by Django 3.1.4 on 2021-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210117_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='github_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='website_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
