# Generated by Django 3.1.4 on 2021-01-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
